'use client';

import { useEffect, useMemo, useState } from 'react';
import { Flower2, MessageCircleHeart, Settings, Sparkles, LogOut, ShieldCheck, Send, Heart, Moon, SlidersHorizontal, X, Volume2, Bell, Palette, Clock3, GlassWater } from 'lucide-react';
import { supabaseBrowser } from '@/lib/supabase-browser';
import AmbientSky from '@/components/AmbientSky';
import MotionPreference from '@/components/MotionPreference';

type Initial = { me: any; people: any[]; settings: any; activeRound: any; stars: any[]; audit: any[]; inviteCode: string };
const seedChoices = ['🌷', '🌼', '🪻', '🌿', '✨'];
const emotes = ['💖', '🤗', '😘', '🥹', '🎉'];
const difficultyCopy: Record<string, string> = { easy: '5 × 5 · 3 targets · no timer', normal: '5 × 5 · 5 targets · default', hard: '5 × 5 · 7 targets · 90 seconds', custom: 'Make it your own' };

export default function RoomApp({ initial }: { initial: Initial }) {
  const [tab, setTab] = useState<'constellation' | 'garden' | 'jar' | 'dock'>('constellation');
  const [stars, setStars] = useState(initial.stars); const [round, setRound] = useState(initial.activeRound);
  const [plants, setPlants] = useState<any[]>([]); const [newPlantIds, setNewPlantIds] = useState<string[]>([]); const [messages, setMessages] = useState<any[]>([]); const [newMessageIds, setNewMessageIds] = useState<string[]>([]); const [pressedStar, setPressedStar] = useState<string>(''); const [bottles, setBottles] = useState<any[]>([]); const [bottleText, setBottleText] = useState(''); const [openBottle, setOpenBottle] = useState<any | null>(null); const [emoteBursts, setEmoteBursts] = useState<any[]>([]);
  const [settingsOpen, setSettingsOpen] = useState(false); const [auditOpen, setAuditOpen] = useState(false); const [settings, setSettings] = useState(initial.settings || {});
  const [message, setMessage] = useState(''); const [seed, setSeed] = useState('🌷'); const [notice, setNotice] = useState(''); const [loadingRound, setLoadingRound] = useState(false); const [inviteOpen, setInviteOpen] = useState(false);
  const [people, setPeople] = useState(initial.people);
  const roomIds = useMemo(() => people.map(person => person.id), [people]);
  async function refreshRoomState() { const response = await fetch('/api/room-state', { cache: 'no-store' }); if (!response.ok) return; const data = await response.json(); setPeople(data.people || []); setRound(data.activeRound || null); setStars(data.stars || []); }

  async function loadBottles() { const response = await fetch('/api/memory-jar', { cache: 'no-store' }); if (!response.ok) return; const data = await response.json(); setBottles(data.bottles || []); }
  async function dropBottle() { const content = bottleText.trim(); if (!content) return; const response = await fetch('/api/memory-jar', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ content }) }); const data = await response.json(); if (!response.ok) return toast(data.error || 'Could not drop this bottle.'); setBottleText(''); await loadBottles(); toast('Your bottle is drifting into the jar.'); }

  async function api(path: string, body?: unknown) { const response = await fetch(path, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); return response.json(); }
  function toast(text: string) { setNotice(text); window.setTimeout(() => setNotice(''), 2800); }

  useEffect(() => {
    const client = supabaseBrowser();
    const channel = client.channel(`room-${initial.me.room_id}`)
      .on('postgres_changes', { event: '*', schema: 'public', table: 'constellation_stars' }, async () => { if (round) { const { data } = await client.from('constellation_stars').select('*').eq('round_id', round.id).order('position'); setStars(data || []); } })
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'garden_plants' }, payload => { setPlants(current => [...current, payload.new]); setNewPlantIds(current => [...current, payload.new.id]); window.setTimeout(() => setNewPlantIds(current => current.filter(id => id !== payload.new.id)), 1800); })
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages' }, payload => { setMessages(current => [...current, payload.new]); setNewMessageIds(current => [...current, payload.new.id]); window.setTimeout(() => setNewMessageIds(current => current.filter(id => id !== payload.new.id)), 1000); })
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'emotes' }, payload => { setEmoteBursts(current => [...current, payload.new]); window.setTimeout(() => setEmoteBursts(current => current.filter(item => item.id !== payload.new.id)), 2200); })
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'memory_bottles' }, () => { void loadBottles(); })
      .on('postgres_changes', { event: 'DELETE', schema: 'public', table: 'memory_bottles' }, () => { void loadBottles(); })
      .on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'users' }, payload => setPeople(current => current.map(person => person.id === payload.new.id ? { ...person, ...payload.new } : person)))
      .subscribe();
    (async () => { const { data: p } = await client.from('garden_plants').select('*').in('user_id', roomIds).order('planted_at'); setPlants(p || []); const { data: m } = await client.from('messages').select('*').in('user_id', roomIds).order('sent_at').limit(100); setMessages(m || []); await loadBottles(); await refreshRoomState(); })();
    const poll = window.setInterval(refreshRoomState, 2500);
    return () => { window.clearInterval(poll); client.removeChannel(channel); };
  }, [initial.me.room_id, roomIds, round]);

  async function startRound(difficulty = settings.difficulty || 'normal') { setLoadingRound(true); const result = await api('/api/game', { action: 'new_round', difficulty }); setLoadingRound(false); if (result.round) { const client = supabaseBrowser(); const { data } = await client.from('constellation_stars').select('*').eq('round_id', result.round.id).order('position'); setRound(result.round); setStars(data || []); await refreshRoomState(); toast(`${difficulty} constellation is ready for both of you.`); } else toast(result.error || 'That constellation could not start.'); }
  async function clickStar(position: number) { const star = stars.find(item => item.position === position); if (star) { setPressedStar(star.id); window.setTimeout(() => setPressedStar(''), 430); } await api('/api/game', { action: 'click_star', position }); await refreshRoomState(); }
  async function plant(event: React.MouseEvent<HTMLDivElement>) { const rect = event.currentTarget.getBoundingClientRect(); const x = ((event.clientX - rect.left) / rect.width) * 100; const y = ((event.clientY - rect.top) / rect.height) * 100; const client = supabaseBrowser(); await client.from('garden_plants').insert({ user_id: initial.me.id, seed_emoji: seed, x, y }); }
  async function sendMessage() { const content = message.trim(); if (!content) return; const client = supabaseBrowser(); await client.from('messages').insert({ user_id: initial.me.id, content }); setMessage(''); }
  async function sendEmote(emote: string) { const client = supabaseBrowser(); await client.from('emotes').insert({ user_id: initial.me.id, emote }); }
  async function saveSettings(next: any) { const client = supabaseBrowser(); const updated = { ...settings, ...next }; await client.from('user_settings').upsert({ user_id: initial.me.id, ...updated }); setSettings(updated); toast('Settings saved.'); }
  async function signOut() { await fetch('/api/room', { method: 'DELETE' }); window.location.href = '/'; }
  async function copyInvite() { try { await navigator.clipboard.writeText(`${window.location.origin}?room=${initial.inviteCode}`); toast('Invite link copied.'); } catch { toast(`Room code: ${initial.inviteCode}`); } }

  const gridSize = round?.grid_size || 5; const locked = stars.filter(star => star.locked_at).length; const partner = people.find(person => person.id !== initial.me.id);
  return <main className={`${settings.theme === 'day' ? 'app day' : 'app'} room-sky`}>
    <MotionPreference reducedMotion={Boolean(settings.reduce_motion)}/><AmbientSky reducedMotion={Boolean(settings.reduce_motion)}/>
    <header className="topbar"><div className="compact-brand"><span className="compact-badge"><Sparkles size={17}/></span><div><p className="eyebrow">our shared sky</p><h1>Constellation</h1></div></div><div className="presence"><i className={partner?.is_online ? 'online' : ''} />{partner?.is_online ? `${partner.username} is here` : 'just you for now'}</div><div className="header-actions"><button className="invite-button" onClick={() => setInviteOpen(true)}>Invite</button><button className="icon-button" onClick={() => setSettingsOpen(true)} aria-label="Open settings"><Settings /></button></div></header>
    {notice && <div className="toast">{notice}</div>}
    <nav className="tabs">{[['constellation', Sparkles], ['garden', Flower2], ['jar', GlassWater], ['dock', MessageCircleHeart]].map(([id, Icon]: any) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><Icon size={18}/><span>{id === 'jar' ? 'Memory Jar' : id[0].toUpperCase() + id.slice(1)}</span></button>)}</nav>
    <section className="content">
      {tab === 'constellation' && <div className={`scene constellation-scene scene-enter`} key={`constellation-${round?.id || 'empty'}`}><SectionHeading icon={<Sparkles size={21}/>} eyebrow="shared puzzle" title={round ? `${round.difficulty} constellation` : 'Choose your first sky'} subtitle={round ? `${locked} of ${round.target_count} stars held together` : 'Set a shared difficulty, then let the first constellation appear.'} action={<button className="soft-button" onClick={() => startRound()} disabled={loadingRound}>{loadingRound ? 'Making a sky…' : 'New constellation'} <span>→</span></button>}/>{round ? <div className="puzzle-wrap"><div className="round-chip"><span>✦</span>{round.difficulty} · {round.target_count} targets{round.time_limit_seconds ? ` · ${round.time_limit_seconds}s` : ''}</div><div className="star-grid" style={{ gridTemplateColumns: `repeat(${gridSize}, 1fr)` }}>{stars.map(star => { const pending = !star.locked_at && (star.clicked_by_user_1 || star.clicked_by_user_2); return <button key={star.id} className={`star ${star.is_target ? 'target' : ''} ${star.locked_at ? 'locked' : ''} ${pending ? 'pending' : ''}`} onClick={() => clickStar(star.position)} aria-label={`Star ${star.position + 1}`}>{star.locked_at ? '✦' : pending ? '◌' : star.is_target ? '·' : ''}</button>})}</div></div> : <Empty icon="✦" title="No constellation yet" text="Start a round and your shared star grid will appear here." />}</div>}
      {tab === 'garden' && <div className="scene scene-enter garden-scene"><SectionHeading icon={<Flower2 size={21}/>} eyebrow="shared garden" title="Leave a little life behind" subtitle="Pick a seed, then tap anywhere in the garden." action={<div className="seed-row">{seedChoices.map(item => <button className={seed === item ? 'seed active' : 'seed'} key={item} onClick={() => setSeed(item)}>{item}</button>)}</div>}/><div className="garden" onClick={plant}>{plants.map(plant => <span key={plant.id} className={`plant ${newPlantIds.includes(plant.id) ? 'plant-new' : ''}`} style={{ left: `${plant.x}%`, top: `${plant.y}%` }}>{plant.seed_emoji}</span>)}{!plants.length && <Empty icon="🌱" title="Your garden is waiting" text="Plant the first little thing for your partner." />}</div></div>}
      {tab === 'jar' && <div className="scene jar-scene scene-enter"><SectionHeading icon={<GlassWater size={21}/>} eyebrow="message in a bottle" title="Memory Jar" subtitle="Leave a small thought for them to find whenever they need it."/><div className="bottle-composer"><textarea value={bottleText} onChange={event => setBottleText(event.target.value.slice(0, 300))} placeholder="Write something they’ll want to keep…" maxLength={300} rows={3}/><div><small>{bottleText.length} / 300</small><button className="soft-button" onClick={dropBottle}>Drop a bottle <span>✦</span></button></div></div>{bottles.length ? <div className="bottle-field">{bottles.map((bottle, index) => <button className="bottle" key={bottle.id} onClick={() => setOpenBottle(bottle)} style={{ transform: `translateY(${(index % 3) * 11}px) rotate(${(index % 2 ? 1 : -1) * (index % 4)}deg)` }} aria-label={`Open a bottle from ${bottle.username}`}>🫙</button>)}</div> : <Empty icon="🫙" title="Your jar is waiting" text="Drop the first little note into your shared sky." />}</div>}
      {tab === 'dock' && <div className="scene dock-scene scene-enter"><SectionHeading icon={<MessageCircleHeart size={21}/>} eyebrow="the dock" title="Close, even from far away" subtitle={partner ? `${partner.username}'s local time will appear here` : 'Invite your partner to dock with you.'}/><div className="messages">{messages.map(item => <div className={`${item.user_id === initial.me.id ? 'message mine' : 'message'} ${newMessageIds.includes(item.id) ? 'message-new' : ''}`} key={item.id}>{item.content}<small>{new Date(item.sent_at).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</small></div>)}{!messages.length && <Empty icon="♡" title="A quiet dock" text="Say the first thing. It will be waiting here." />}</div><div className="emotes">{emotes.map(emote => <button key={emote} onClick={() => sendEmote(emote)}>{emote}</button>)}</div><div className="composer"><input value={message} onChange={event => setMessage(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') sendMessage(); }} placeholder="Say something soft…"/><button onClick={sendMessage} aria-label="Send message"><Send size={18}/></button></div></div>}
    </section>
    {emoteBursts.map(item => <div className="emote-burst" key={item.id}>{item.emote}</div>)}
    {openBottle && <div className="sheet-backdrop invite-backdrop" onClick={event => { if (event.target === event.currentTarget) setOpenBottle(null); }}><div className="invite-card bottle-reveal"><button className="close" onClick={() => setOpenBottle(null)}><X/></button><span className="section-icon"><GlassWater size={20}/></span><p className="eyebrow">a bottle from {openBottle.username}</p><h2>A little thing to keep</h2><p className="bottle-note">{openBottle.content}</p><small>{relativeTime(openBottle.created_at)}</small></div></div>}
    {inviteOpen && <div className="sheet-backdrop invite-backdrop" onClick={event => { if (event.target === event.currentTarget) setInviteOpen(false); }}><div className="invite-card"><button className="close" onClick={() => setInviteOpen(false)}><X/></button><span className="section-icon"><Heart size={20}/></span><p className="eyebrow">your private room</p><h2>Send them this code</h2><p>They can enter it from the Join their room panel on their device.</p><div className="invite-code">{initial.inviteCode}</div><button className="soft-button" onClick={copyInvite}>Copy invite link</button></div></div>}
    {settingsOpen && <SettingsSheet settings={settings} me={initial.me} close={() => setSettingsOpen(false)} save={saveSettings} newRound={startRound} signOut={signOut} openAudit={() => setAuditOpen(true)} />}
    {auditOpen && <AuditSheet events={initial.audit} close={() => setAuditOpen(false)} />}
  </main>;
}

function relativeTime(value: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return 'just now'; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; return `${Math.floor(seconds / 86400)}d ago`; }

function SectionHeading({ icon, eyebrow, title, subtitle, action }: { icon: React.ReactNode; eyebrow: string; title: string; subtitle: string; action?: React.ReactNode }) { return <div className="scene-heading"><div className="section-title"><span className="section-icon">{icon}</span><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{subtitle}</p></div></div>{action && <div className="scene-action">{action}</div>}</div>; }
function Empty({ icon, title, text }: { icon: string; title: string; text: string }) { return <div className="empty"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="toggle-row"><span>{label}</span><button type="button" role="switch" aria-checked={checked} className={checked ? 'toggle on' : 'toggle'} onClick={() => onChange(!checked)}><i/></button></label>; }
function SettingsSheet({ settings, me, close, save, newRound, signOut, openAudit }: any) { const [draft, setDraft] = useState(settings); const set = (next: any) => { const value = { ...draft, ...next }; setDraft(value); save(next); }; return <div className="sheet-backdrop" onClick={event => { if (event.target === event.currentTarget) close(); }}><aside className="sheet"><div className="sheet-top"><div><span className="section-icon"><SlidersHorizontal size={20}/></span><p className="eyebrow">shared room settings</p><h2>Our little space</h2></div><button className="close" onClick={close} aria-label="Close settings"><X/></button></div><section><h3>Account</h3><p className="muted">Signed in as {me.username}</p><button className="line-button" onClick={signOut}><LogOut size={16}/>Sign out</button></section><section><h3>Constellation difficulty</h3><p className="control-help">Choosing a level begins the next shared constellation for both of you.</p><div className="difficulty-list">{['easy','normal','hard','custom'].map(level => <button key={level} className={draft.difficulty === level ? 'selected' : ''} onClick={() => { set({ difficulty: level }); newRound(level); }}><strong>{level[0].toUpperCase() + level.slice(1)}</strong><small>{difficultyCopy[level]}</small></button>)}</div></section><section><h3><Volume2 size={16}/> Sound</h3><Toggle label="Sound enabled" checked={draft.sound_enabled ?? true} onChange={value => set({ sound_enabled: value })}/><Toggle label="Emote sound" checked={draft.emote_sound_enabled ?? true} onChange={value => set({ emote_sound_enabled: value })}/></section><section><h3><Bell size={16}/> Notifications</h3><Toggle label="Notifications enabled" checked={draft.notifications_enabled ?? true} onChange={value => set({ notifications_enabled: value })}/><div className="setting-inline"><Clock3 size={15}/><span>Quiet hours are stored for later push notifications.</span></div></section><section><h3><Palette size={16}/> Appearance</h3><Toggle label="Reduce motion" checked={draft.reduce_motion ?? false} onChange={value => set({ reduce_motion: value })}/><div className="theme-row"><button className={draft.theme === 'night' ? 'selected' : ''} onClick={() => set({ theme: 'night' })}>Night</button><button className={draft.theme === 'day' ? 'selected' : ''} onClick={() => set({ theme: 'day' })}>Day</button></div></section><section><h3><ShieldCheck size={16}/> Transparency</h3><button className="line-button" onClick={openAudit}>View our audit log</button></section></aside></div> }
function AuditSheet({ events, close }: any) { return <div className="sheet-backdrop" onClick={event => { if (event.target === event.currentTarget) close(); }}><aside className="sheet audit"><div className="sheet-top"><div><span className="section-icon"><ShieldCheck size={20}/></span><p className="eyebrow">transparency log</p><h2>Our room activity</h2></div><button className="close" onClick={close}><X/></button></div>{events.map((event: any) => <div className="audit-row" key={event.id}><strong>{event.event_type.replaceAll('_', ' ')}</strong><small>{new Date(event.created_at).toLocaleString()}</small></div>)}{!events.length && <Empty icon="⌁" title="Nothing to show" text="Security events will appear here." />}</aside></div> }
